### ISSUE TITLE
Import external resources not importing RDF file

### ISSUE THREAD

**Issue by cmachingauta** [ihsn/editor#3]
![image](https://github.com/ihsn/editor/assets/7582929/260c2ff2-0b92-4cbc-904a-61c0f775191a)
Import external resources does not seem to be importing RDF

To reproduce issue
[NGA_2021-2023_NLPS_v05_M.zip](https://github.com/ihsn/editor/files/11984262/NGA_2021-2023_NLPS_v05_M.zip)

Click External Resources then click Import
Select RDF file (Use attached rdf with resources listed on https://microdata.worldbank.org/index.php/catalog/4444/related-materials)
Click Import file

Expected result:
External resources shows the imported resources
Actual result - no resources imported.

**Comment by mah0001** [comment]
fixed
